default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: GET

default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login" }

default_authorization:
    path: /check_token
    defaults: { _controller: "AppBundle:Default:authorization" }
